#!/bin/sh
# Copyright (C) 2016 The Meme Factory, Inc.  http://www.meme.com/
#
#    This file is part of PLHDB2.
#
#    PLDHB2 is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Babase.  If not, see <http://www.gnu.org/licenses/>.
#
# Karl O. Pinc <kop@meme.com>
#
# Syntax: copy_tables fromdb todb
#
# Remarks:
#   Copies the database content.

sourcedb=$1
targetdb=$2

copy_table() {
  fromdb=$1
  todb=$2
  table=$3

  pg_dump -U plhdb_admin -Fc --data-only \
          --table=plhdb.$table --dbname=$fromdb \
    | pg_restore -U plhdb_admin --dbname $todb
}

for t in site taxon study ; do
  copy_table $sourcedb $targetdb $t
done
