#!/bin/sh
# Copyright (C) 2016 The Meme Factory, Inc.  http://www.meme.com/
#
#    This file is part of PLHDB2.
#
#    PLDHB2 is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with PLHDB2.  If not, see <http://www.gnu.org/licenses/>.
#
# Karl O. Pinc <kop@meme.com>
#
# Remarks:
#   More or less, one-off program.

psql --no-align -F "$(printf '\t')" -U plhdb_admin old_plhdb <<EOF

select account.email
     , account.first_name
     , account.last_name
     , case when account.password = 'non_working_password'
              then 'no'
            else 'yes'
       end as haspwd
     , account.admin
     , permission.study
     , studyinfo.commonname
     , permission.access
  from auth.account
       left outer join auth.permission
         on (account.user_oid = permission.user_oid)
       left outer join public.studyinfo
         on (permission.study = studyinfo.studyid)
  order by case when account.password = 'non_working_password'
                  then 1
                else 0
           end
         , account.email
         , permission.study;
EOF
