#!/bin/sh
# Copyright (C) 2016 The Meme Factory, Inc.  http://www.meme.com/
#
#    This file is part of PLHDB2.
#
#    PLHDB2 is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with PLHDB2.  If not, see <http://www.gnu.org/licenses/>.
#
# Karl O. Pinc <kop@meme.com>
#
# Remarks:
#   More or less, one-off program.
#
#   Must be run after the new databases (or at least the new roles)
#   are created.
#
# Bugs:
#  The comment on the plhdb_demo db does not restore.  We don't care.

ADMIN=plhdb_admin

loaddb() {
  db=$1
  newdb=old_$db

  printf "drop database if exists $newdb;\n" \
    | psql -U $ADMIN template1

  createdb -U $ADMIN $newdb "Copy of old $db db before conversion."

  { printf "revoke connect on database $newdb from public;\n"
    printf "revoke connect on database $newdb from demo_user;\n"

    printf "grant connect on database $newdb to plhdb_managers;\n"
  } | psql -U $ADMIN template1

  dumpfile=/srv/apps/old_system_db_dumps/$db.custom
  pg_restore --no-privileges --no-owner -U $ADMIN -d $newdb $dumpfile

  { for schema in audit auth bulkimp plhdb public sandbox ; do
      printf "grant usage on schema $schema to plhdb_managers;\n"
      printf "grant select on all tables in schema $schema \n"
      printf "             to plhdb_managers;\n"
    done
    printf 'alter database %s ' $newdb
    printf 'set search_path to '
    printf 'public,plhdb,auth,audit,bulkimp,sandbox,"$user";\n'
  } \
  | psql -U $ADMIN $newdb
}

loaddb plhdb
loaddb plhdb_demo
